### ISSUE TITLE
Example fail to run if xml is moved to file

### ISSUE THREAD

**Issue by furio** [libxmljs/libxmljs#219]
I've altered the default snippet to read the xml from a file like this:

```
var libxmljs = require("libxmljs");
var xml =  '<?xml version="1.0" encoding="UTF-8"?>' +
           '<root>' +
               '<child foo="bar">' +
                   '<grandchild baz="fizbuzz">grandchild content</grandchild>' +
               '</child>' +
               '<sibling>with content!</sibling>' +
           '</root>';

var xmlTwo = require('fs').readFileSync('./test/test.xml', {encoding: 'utf-8'});

var xmltoParse = xmlTwo;
console.log(xmltoParse);

var xmlDoc = libxmljs.parseXml(xmltoParse);

// xpath queries
var gchild = xmlDoc.get('//grandchild');

console.log(gchild.text());  // prints "grandchild content"

var children = xmlDoc.root().childNodes();
var child = children[0];

console.log(child.attr('foo').value()); // prints "bar"
```

Result is this:

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <child foo="bar">
        <grandchild baz="fizbuzz">grandchild content</grandchild>
    </child>
    <sibling>with content!</sibling>
</root>
grandchild content

/media/extraSpace/furio/gitRoot/xmltest/test.js:25
console.log(child.attr('foo').value()); // prints "bar"
                              ^
TypeError: Cannot call method 'value' of null
    at Object.<anonymous> (/media/extraSpace/furio/gitRoot/xmltest/test.js:25:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

If i change

```
var xmltoParse = xmlTwo;
```

to

```
var xmltoParse = xml;
```

everything works as expected.

**Comment by skrosoft** [comment]
I understand the reason but I agree with @furio , this is really disturbing.
