### ISSUE TITLE
Install failed - unsupported node version ?

### ISSUE THREAD

**Issue by phtrivier** [libxmljs/libxmljs#246]
Installation of libxmljs fails on my machine ; I get many errors, including things like this when node-gyp runs  

```
../src/libxmljs.cc:137:19: error: ‘NewSymbol’ is not a member of ‘v8::String’
       target->Set(v8::String::NewSymbol("libxml"), target);
```

Extract from report : 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/phtrivier/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "node" "/home/phtrivier/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/phtrivier/prj/platform/git/av-ui/av-accounts/node_modules/node-recurly/node_modules/js2xml/node_modules/libxmljs
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
```

This looks like I don't have a supported version of node, which one should I downgrade / upgrade to ?

Thanks

**Comment by mrchimp** [comment]
Does libxmljs support Node 4.2.2? I'm having the same problem.
