### ISSUE TITLE
xml schema does not validate correctly with regard xs:include/@schemaLocation (wrong base path)

### ISSUE THREAD

**Issue by rkoberg** [libxmljs/libxmljs#275]
I have a script in a directory. At the same level as the script I have mathml2/mathml2.xsd -- a valid, W3C schema. The XSD gets parsed without error (apparently no inclusion happens at this point), but when I try to validate an XML document, I get an validation error:

```
mathmlXsdDoc { errors: [] }
mathmlDoc { errors: [] }

/my/project/conversion/psoc/node_modules/libxmljs/lib/document.js:73
    return this._validate(xsd);
                ^
Error: Invalid XSD schema
    at Document.validate (/my/project/conversion/psoc/node_modules/libxmljs/lib/document.js:73:17)
    at /my/project/conversion/psoc/mathml-validate-report.js:51:20
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

If I move the contents of the mathml2 directory to be at the same level as the script, validation is working.

In other words, the base path to resolve the xs:include/@schemaLocation should be using the including XSD, but it is using the script as the base path. This probably has to do with using a string as the source rather than a file. I saw a stackoverflow post with someone using parseXmlFile, but that doesn't appear as an option from what I can see. Is there some way to load from a file to have libxml know where to base its resolver? Or pass the base path/file location along with the XML string to use for resolution? I don't really understand the C source to dig much deeper.

**Comment by Arlen22** [comment]
I'm also having this problem and would really like a resolution. Shouldn't the includes be relative to the location of the file? But I'm not sure how to specify what that base path is.

**Comment by rchipka** [comment]
Try setting the `baseUrl` [option](https://github.com/libxmljs/libxmljs/blob/779417cb86c36eafd337765a3c310194a3e20a03/src/xml_document.cc#L420). Not sure if it will work, but it's worth a try.

**Comment by joneldiablo** [comment]
Question, if the schemaLocation points to any url like: `xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd"`
have I need download the xsd files and put in some folder and use baseUrl  with the path to the folder?

**Comment by luckydonald** [comment]
@joneldiablo [This stackoverflow answer](https://stackoverflow.com/a/67390464/3423324) seems to indicate that's a yes.
