### ISSUE TITLE
unable to install due to node-gyp rebuild issues

### ISSUE THREAD

**Issue by raja-i4** [libxmljs/libxmljs#401]
windows 8 - 64 bit.

I have the following issue. tried many times, installed msbuild tools , re-installed node as well. but didn't work.

![image](https://cloud.githubusercontent.com/assets/17741219/14849377/3b1f5d14-0c90-11e6-8587-c0997ec22f8a.png)

**Comment by BernhardBezdek** [comment]
Same issue on OSX with latest node.js version (6.0.0)

```
rwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

```
46281 verbose stack Error: libxmljs@0.17.1 install: `node-gyp rebuild`
46281 verbose stack Exit status 1
46281 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:244:16)
46281 verbose stack     at emitTwo (events.js:106:13)
46281 verbose stack     at EventEmitter.emit (events.js:191:7)
46281 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
46281 verbose stack     at emitTwo (events.js:106:13)
46281 verbose stack     at ChildProcess.emit (events.js:191:7)
46281 verbose stack     at maybeClose (internal/child_process.js:850:16)
46281 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
46282 verbose pkgid libxmljs@0.17.1
```

**Comment by BernhardBezdek** [comment]
#400 solved it for me

**Comment by osambhus** [comment]
+1.
Same issue with node v6.0.0 and npm 3.8.6 on linux. The ```adriancooney/libxmljs``` fork doesn't work either. 


```
make: Entering directory '/home/ec2-user/vastValidator/consumer-edge/creativeAddOn/vast-debugger/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
make: cc: Command not found
make: *** [Release/obj.target/libxml/vendor/libxml/buf.o] Error 127
make: Leaving directory '/home/ec2-user/vastValidator/consumer-edge/creativeAddOn/vast-debugger/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.1.10-17.31.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/vastValidator/consumer-edge/creativeAddOn/vast-debugger/node_modules/libxmljs
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "libxmljs"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.17.1 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/vastValidator/consumer-edge/creativeAddOn/vast-debugger/npm-debug.log
```

**Comment by hildjj** [comment]
Dup of #400.  Fixed by #402.

**Comment by grssnbchr** [comment]
The issue might be with an outdated version of gcc, see https://github.com/libxmljs/libxmljs/issues/413#issuecomment-221299374

**Comment by hildjj** [comment]
@osambhus your trace says `cc: Command not found`.  Install a compiler.

**Comment by rchipka** [comment]
Fixed
