### ISSUE TITLE
Unable to install libxmljs on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rcpfuchs** [libxmljs/libxmljs#428]
Hey, I rented a virtual webserver running Ubuntu 14.04 LTS an wanted to publish my node project. I use libxmljs for some xml parsing. Unfortunatly `npm install libxmljs` fails.
I also installed a parallels vm on my mac to see if some miscofiguration could lead to this error. On a clean install of ubunutu I run the following commands:

1. apt-get install curl, 
2. curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
3. nvm install node

node and npm are now installed with their newest versions.

```
npm install libxmljs

> libxmljs@0.18.0 install /root/nodejs/tmp/node_modules/libxmljs
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/root/nodejs/tmp/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
make: cc: Command not found
make: *** [Release/obj.target/libxml/vendor/libxml/buf.o] Error 127
make: Leaving directory `/root/nodejs/tmp/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-042stab117.8
gyp ERR! command "/root/.nvm/versions/node/v6.3.1/bin/node" "/root/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nodejs/tmp/node_modules/libxmljs
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-042stab117.8
npm ERR! argv "/root/.nvm/versions/node/v6.3.1/bin/node" "/root/.nvm/versions/node/v6.3.1/bin/npm" "install" "libxmljs"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/nodejs/tmp/npm-debug.log

```

Does anyone have an idea what is going wrong?

Best regards, Simon

**Comment by bcomnes** [comment]
you probably don't have gcc 4.8 installed. See https://github.com/libxmljs/libxmljs/blob/master/.travis.yml for an example of installing gcc on travis.
