### ISSUE TITLE
error occurred when testing public XML file

### ISSUE THREAD

**Issue by wk0206** [libxmljs/libxmljs#434]
On linux system:

```
node -v
v5.12.0
npm -v
3.8.6
```

when testing [link](https://raw.githubusercontent.com/wk0206/testPorject2/master/TestData/SigmodRecord.xml) give an error message.
This file is download from [cs.washington.edu](http://www.cs.washington.edu/research/xmldatasets/www/repository.html) with name SigmodRecord.xml

```
return bindings.fromXml(string, options || {});
Error: Entity 'uuml' not defined

    at Error (native)
    at Object.module.exports.fromXml (/usr/lib/node_modules/xml2csv/node_modules/libxmljs/lib/document.js:167:21)
    at addChild (/usr/lib/node_modules/xml2csv/requestHandlers.js:338:24)
    at recFunc (/usr/lib/node_modules/xml2csv/requestHandlers.js:619:33)
    at Object.treatXMLFile (/usr/lib/node_modules/xml2csv/requestHandlers.js:1092:19)
    at Request._callback (/usr/lib/node_modules/xml2csv/xml2csv.js:57:37)
    at Request.self.callback (/usr/lib/node_modules/xml2csv/node_modules/request/request.js:121:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/lib/node_modules/xml2csv/node_modules/request/request.js:985:14)
```

**Comment by hildjj** [comment]
Can you search for `&uuml;` in the input?  If found, you probably need to ensure you're using the correct DTD from the linked page.

**Comment by rchipka** [comment]
Will reopen on new information
