### ISSUE TITLE
__fprintf_chk: symbol not found

### ISSUE THREAD

**Issue by JoeKomputer** [libxmljs/libxmljs#479]
Getting a new error when using v0.18.7 (was working with 0.18.6 previously)
```
[16:58:40] Error: Error relocating myproj/node_modules/libxmljs/build/Release/xmljs.node: __fprintf_chk: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (myproj/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (myproj/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (myproj/node_modules/libxmljs/index.js:4:16)
```

**Comment by WClouds** [comment]
I meet the same error!

**Comment by tuananh** [comment]
Any chance you use it with Alpine OS ?

**Comment by JoeKomputer** [comment]
Yes I am using Alpine

**Comment by tuananh** [comment]
@JoeKomputer this issue happened because alpine uses musl instead of glibc.

there are 2 ways to solve this

* install glibc on alpine (not sure about the status of this project, last i checked, it didn't work very well)

* use another distro. i have very good experience with bitnami docker node (based on minideb , using glibc). Even though alpine image is small but after installing everything, the final size between bitnami node and alpine node are not much different

**Comment by marpada** [comment]
+1, would very much like keep using alpine

**Comment by throrin19** [comment]
+1, for us it's a requirement to use alpine but, with the `xmljs.node: __fprintf_chk` error, it's not possible.
Nobody have the solution yet ?

**Comment by seifer08ms** [comment]
It seem we can only include source of glibc in the progress of our program. Any glibc-compat alpine-docker doesn't work for this issue.

**Comment by arankhem** [comment]
Did anyone got the work around for this?

**Comment by rchipka** [comment]
According to [this page](http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/libc---fprintf-chk-1.html), `__fprintf_chk` is an internal interface for memory-safe fprintf and is not defined in the source headers (only in the binary)

Assuming you're using the pre-built Linux binaries for libxmljs, you'll need to make sure that the libc binary you're using contains `__fprintf_chk`

Apparently Alpine uses `alpine-pkg-glibc`, which "utilizes a custom built glibc binary based on the vanilla glibc source"

Chances are that the `alpine-pkg-glibc` compiled binary doesn't include the functions in the glibc [debug](https://github.com/lattera/glibc/tree/master/debug) directory, which includes `fprintf_chk.c`

Potentially related issues:
https://github.com/grycap/scar/issues/28
https://github.com/gliderlabs/docker-alpine/issues/149
