### ISSUE TITLE
New test failures with node 8.3.0

### ISSUE THREAD

**Issue by tomhughes** [libxmljs/libxmljs#485]
There appear to be two test failures, both of which appear to be memory leaks, with node 8.3.0 that weren't present with node 8.2.1 namely:

```
✖ inaccessible_document_freed_when_node_freed
AssertionError [ERR_ASSERTION]: false == true
    at Object.ok (/usr/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.inaccessible_document_freed_when_node_freed (/builddir/build/BUILD/package/test/memory_management.js:30:12)
    at /usr/lib/node_modules/nodeunit/lib/core.js:232:20
    at /usr/lib/node_modules/async/lib/async.js:726:13
    at /usr/lib/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/async/lib/async.js:269:32
    at /usr/lib/node_modules/async/lib/async.js:44:16
    at /usr/lib/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/async/lib/async.js:167:37
    at Object.module.exports.setUp (/builddir/build/BUILD/package/test/memory_management.js:9:5)
```
and:

```
✖ inaccessible_tree_freed
AssertionError [ERR_ASSERTION]: false == true
    at Object.ok (/usr/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.module.exports.inaccessible_tree_freed (/builddir/build/BUILD/package/test/memory_management.js:51:12)
    at /usr/lib/node_modules/nodeunit/lib/core.js:232:20
    at /usr/lib/node_modules/async/lib/async.js:726:13
    at /usr/lib/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/async/lib/async.js:269:32
    at /usr/lib/node_modules/async/lib/async.js:44:16
    at /usr/lib/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/async/lib/async.js:167:37
    at Object.module.exports.setUp (/builddir/build/BUILD/package/test/memory_management.js:9:5)
```

**Comment by rchipka** [comment]
Can you try rebuilding libxmljs using the latest version of [NAN](https://github.com/nodejs/nan)?

**Comment by tomhughes** [comment]
Already on 2.6.2 which appears to be the least I'm afraid :-(

**Comment by rchipka** [comment]
You may have 2.6.2 installed, but are you sure that the actual libxmljs build process used NAN v2.6.2?

The package.json says to install use version `~2.5.0`

**Comment by tomhughes** [comment]
This is building the Fedora package so it's running in a clean chroot with only 2.6.2 installed and no network access so I'm pretty sure, yes.

**Comment by rchipka** [comment]
Can you post the output of `node-gyp rebuild`

**Comment by tomhughes** [comment]
It's all in the build log as https://kojipkgs.fedoraproject.org/work/tasks/8870/21148870/build.log although we actually do `node-gyp configure` and `node-gyp build`.

It will also look a bit odd because the vendored libxml has been removed and binding.gyp has been patched to link against the system one - the version of that hasn't changed since a build a few days ago with node 8.2.1 that worked though (see https://kojipkgs.fedoraproject.org/packages/nodejs-libxmljs/0.18.2/5.fc27.1/data/logs/x86_64/build.log for output from that).

**Comment by tomhughes** [comment]
I've run a travis build of master now and that shows the same result: https://travis-ci.org/tomhughes/libxmljs/jobs/263195399

**Comment by MylesBorins** [comment]
We are noticing these failures in the Node CITGM smoke test suite as well. We are going to turn off testing this library until the test failures have been fixed
