### ISSUE TITLE
Installation failed on Centos 7 with Node 6.12.0

### ISSUE THREAD

**Issue by skumar568** [libxmljs/libxmljs#499]
Hi,

Getting below error while installing libxmljs@latest with Node 6.12.0 on Centos 7. Below is the error:-
```
make: Entering directory `/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build'
make: *** No rule to make target `../.node-gyp/6.12.0/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release"
gyp ERR! cwd /home/centos/lmStubDocker/LEAP/node_modules/libxmljs
gyp ERR! node -v v6.12.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/centos/lmStubDocker/LEAP/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
```

Complete stack trace attached. I tried installing NAN and touch module, but of no help.

Regards,
Sanjeev
[libxmljs_installationFailure.txt](https://github.com/libxmljs/libxmljs/files/1567596/libxmljs_installationFailure.txt)

**Comment by rchipka** [comment]
`WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.12.0"`

Can you try installing as non-root?
