### ISSUE TITLE
 Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by shubsaini09** [libxmljs/libxmljs#502]
Error i am getting

```
console.log(gchild.text());
                  ^
TypeError: Cannot read property 'text' of undefined
    at Object.<anonymous> (C:\PROJECTS\cciAWS\xml\libxml.js:13:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
My sample xml is 
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Header/>
<soapenv:Body>
<GetContactResponse xmlns="http://mydomain/mypath">
	<GetContactOutput>
		<ContactItem>
			<FullName>Andrew D1</FullName>
			<WorkPhoneNumber>91472006</WorkPhoneNumber>
			<MobilePhoneNumber>91472001</MobilePhoneNumber>
			<FaxNumber>91412006</FaxNumber>
			<Email>abc@a.com</Email>
		</ContactItem>
		<ContactItem>
			<FullName>Andrew D1</FullName>
			<WorkPhoneNumber>9121006</WorkPhoneNumber>
			<MobilePhoneNumber>9112001</MobilePhoneNumber>
			<FaxNumber>91412006</FaxNumber>
			<Email>abc@a.com</Email>
		</ContactItem>
	</GetContactOutput>
</GetContactResponse>
</soapenv:Body>
</soapenv:Envelope>
```
Code i am using
```
var xmlDoc = libxmljs.parseXml(xml);
var gchild = xmlDoc.get('//Email');
console.log(gchild.text());
```
Things work fine if my attribute in `<GetContactResponse xmlns="http://mydomain/mypath">` is not `xmlns` and something else. What is the issue here? Any help to parse it?

**Comment by tuananh** [comment]
I created a similar issue, you may want to take a look at solution there. https://github.com/libxmljs/libxmljs/issues/338

**Comment by shubsaini09** [comment]
@tuananh Is there no other way instead of that root hack you used?

**Comment by tuananh** [comment]
there is

https://github.com/libxmljs/libxmljs/issues/338#issuecomment-140790939

**Comment by shubsaini09** [comment]
@tuananh I don't want to hard code my xpath or ns_uri. Suppose you want to get first Email value then how would you do it?

`xmlDoc.get('xmlns:Email', "http://mydomain/mypath");`

**Comment by Jeff457** [comment]
@shubsaini09 
The comment by abimelex from #338 works to get the first Email value.

```
var xmlDoc = libxmljs.parseXml(xml);
var email = xmlDoc.get("//*[local-name(.)='Email']");
email.text();  // 'abc@a.com'
```
