### ISSUE TITLE
Premature end of data in tag

### ISSUE THREAD

**Issue by shubsaini09** [libxmljs/libxmljs#504]
```
var xmlString = "<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:soapenc='http://schemas.xmlsoap.org/soap/encoding/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><soapenv:Header/><soapenv:Body><GetContactResponse xmlns='http://www.yy.com/sdfg/schema/v2'><GetContactOutput><ContactItem><ContactGUID>9068281</ContactGUID><RecordSourceKey><Pkey>258|S</Pkey><WorkPhoneNumber>9098</WorkPhoneNumber><MobilePhoneNumber>5048</MobilePhoneNumber><FaxNumber>9147</FaxNumber><Email>xyz@yy.com</Email></ContactItem></GetContactOutput></GetContactResponse></soapenv:Body></soapenv:Envelope>"

xmlString = xmlString.replace(/<([a-zA-Z0-9 ]+)(?:xml)ns=\".*\"(.*)>/g, "<$1$2>");
let email = libxmljs.parseXml(xmlString);
email = email.get("//Email");
email = email.text();
console.log(email)

Error:

C:\PROJECTS\cci\recurse\node_modules\libxmljs\lib\document.js:168
    return bindings.fromXml(string, options || {});
                    ^

Error: Premature end of data in tag Envelope line 1

    at Error (native)
    at Object.module.exports.fromXml (C:\PROJECTS\cci\recurse\node_modules\libxmljs\lib\document.js:168:21)
    at Object.<anonymous> (C:\PROJECTS\cci\recurse\libxml.js:13:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

```

**Comment by rchipka** [comment]
Please provide the XML content after doing `.replace`

**Comment by shubsaini09** [comment]
It was the problem with my xml. My xml was invalid, things work fine when corrected. 

Thanks for your time :)
