### ISSUE TITLE
Cannot compile in Node 10.x on OS X

### ISSUE THREAD

**Issue by ThaliaBarrera** [libxmljs/libxmljs#511]
```sh
npm install -g libxml  

> libxml@0.0.7 preinstall /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxml
> ./build.sh

./build.sh: line 8: node-waf: command not found
./build.sh: line 9: node-waf: command not found
cp: build/Release/o3.node: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxml@0.0.7 preinstall: `./build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxml@0.0.7 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mj/.npm/_logs/2018-05-30T23_28_22_971Z-debug.log
➜  foo git:(master) ✗ npm install -g libxmljs

> libxmljs@0.18.9-pre0 install /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.9-pre0 and node@10.3.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.9-pre0 and node@10.3.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
rm: ./Release/.deps/Release/obj.target/xmljs/src/libxmljs.o.d.raw: No such file or directory
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/mj/.nvm/versions/node/v10.3.0/bin/node" "/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release"
gyp ERR! cwd /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/mj/.nvm/versions/node/v10.3.0/bin/node /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/mj/.nvm/versions/node/v10.3.0/bin/node" "/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs
node-pre-gyp ERR! node -v v10.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/mj/.nvm/versions/node/v10.3.0/bin/node /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.18.9-pre0 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.9-pre0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mj/.npm/_logs/2018-05-30T23_28_51_495Z-debug.log
➜  foo git:(master) ✗ In file included from ../src/xml_attribute.cc:2:
In file included from ../src/xml_attribute.h:5:
../src/libxmljs.h:7:10: fatal error: 'nan.h' file not found
#include "nan.h"
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/xmljs/src/xml_attribute.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/mj/.nvm/versions/node/v10.3.0/bin/node" "/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs/build/Release"
gyp ERR! cwd /Users/mj/.nvm/versions/node/v10.3.0/lib/node_modules/libxmljs
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

➜  foo git:(master) ✗ 
➜  foo git:(master) ✗ nvm use 8
Now using node v8.9.4 (npm v5.6.0)
➜  foo git:(master) ✗ npm install -g libxmljs

> libxmljs@0.18.9-pre0 install /Users/mj/.nvm/versions/node/v8.9.4/lib/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.9-pre0 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.9-pre0/node-v57-darwin-x64.tar.gz 
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
  CXX(target) Release/obj.target/xmljs/src/xml_element.o
  CXX(target) Release/obj.target/xmljs/src/xml_comment.o
  CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
  CXX(target) Release/obj.target/xmljs/src/xml_node.o
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
../src/xml_sax_parser.cc:130:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(this->handle(), v8::Local<v8::Function>::Cast(emit_v), argc + 1, args);
         ^
../node_modules/nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../node_modules/nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
  CXX(target) Release/obj.target/xmljs/src/xml_text.o
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/buf.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/catalog.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/dict.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/encoding.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/entities.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/error.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/globals.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/hash.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/HTMLparser.o
../vendor/libxml/HTMLparser.c:4447:41: warning: missing field 'begin_pos' initializer [-Wmissing-field-initializers]
    htmlParserNodeInfo node_info = { 0, };
                                        ^
1 warning generated.
  CC(target) Release/obj.target/xmljs/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/legacy.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/list.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/parser.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/pattern.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/SAX.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/tree.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/threads.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/uri.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/valid.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xlink.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xpath.o
In file included from ../vendor/libxml/xpath.c:462:
../vendor/libxml/timsort.h:405:65: warning: comparison of integers of different signs: 'long long' and 'const size_t' (aka 'const unsigned long') [-Wsign-compare]
    if ((stack_curr == 2) && (stack[0].length + stack[1].length == size)) {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
In file included from ../vendor/libxml/xpath.c:476:
../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
trio_is_negative
^
3 warnings generated.
  CC(target) Release/obj.target/xmljs/vendor/libxml/xpointer.o
  SOLINK(target) Release/xmljs.node
+ libxmljs@0.18.9-pre0
added 116 packages in 52.172s
```

**Comment by GoodBoy962** [comment]
the same for me

**Comment by jf-bloom** [comment]
I was having a similar build issue on OS X and on linux.

node v10.3.0
npm 6.1.0
libxmljs 0.9.1

I was able to get this to work using `npm install --build-from-source ` on both OS X and linux. I can alos build the project with no errors if I clone libxmljs repo locally.

Here was the error on linux (`npm install` without `--build-from-source`):
```
> libxmljs@0.19.1 install /var/www/XXXXXX/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.1/node-v64-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.1/node-v64-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.1/node-v64-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.1 and node@10.3.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.1/node-v64-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.1 and node@10.3.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
make: Entering directory `/var/www/XXXXXX/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: Entering directory `/var/www/XXXXXX/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
sed: can't read ./Release/.deps/Release/obj.target/xmljs/src/libxmljs.o.d.raw: No such file or directory
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
rm: cannot remove './Release/.deps/Release/obj.target/xmljs/src/libxmljs.o.d.raw': No such file or directory
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory `/var/www/XXXXXX/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v10.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/opt/node-v10.3.0-linux-x64/bin/node" "/opt/node-v10.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/var/www/XXXXXX/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/var/www/XXXXXX/node_modules/libxmljs/build/Release" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /var/www/XXXXXX/node_modules/libxmljs
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/node-v10.3.0-linux-x64/bin/node /opt/node-v10.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/var/www/XXXXXX/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/var/www/XXXXXX/node_modules/libxmljs/build/Release --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/XXXXXX/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.9.93-linuxkit-aufs
node-pre-gyp ERR! command "/opt/node-v10.3.0-linux-x64/bin/node" "/var/www/XXXXXXs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /var/www/XXXXXX/node_modules/libxmljs
node-pre-gyp ERR! node -v v10.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/opt/node-v10.3.0-linux-x64/bin/node /opt/node-v10.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/var/www/XXXXXX/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/var/www/XXXXXX/node_modules/libxmljs/build/Release --napi_version=3 --node_abi_napi=napi' (1)
In file included from ../src/xml_attribute.cc:2:0:
../src/xml_attribute.h:7:27: fatal error: xml_namespace.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/xmljs/src/xml_attribute.o] Error 1
make: Leaving directory `/var/www/XXXXXX/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v10.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/opt/node-v10.3.0-linux-x64/bin/node" "/opt/node-v10.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/var/www/XXXXXX/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/var/wwwXXXXXX/node_modules/libxmljs/build/Release" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /var/www/XXXXXX/node_modules/libxmljs
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.19.1 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by richtera** [comment]
Is there any news on this, it still failed for me and the commented "workarounds" don't seem to work.

**Comment by rezonant** [comment]
Hrm, the workaround of using `npm install --build-from-source` worked for me on Ubuntu (digital ocean). What platform are you building on? Did the error message change with --build-from-source?

**Comment by richtera** [comment]
I am running plain Mac OS with nvm running v10.7.0.
I added a gist with the failed and successful package.json and build output. Very strange.
https://gist.github.com/richtera/3855873f20df2c77a5fcb589453469d7
What's interesting is that the ```yarn add libxmljs``` only fails in the context of my package.json. If I create a new empty directory and just do ```yarn add libxmljs``` it works fine.
Same node, npm and yarn
```sh
$ node -v
v10.7.0
$ npm -v
6.3.0
$ yarn -v
1.9.4
```

**Comment by richtera** [comment]
Again both cases (and I tried another package.json with the same problem) work with v9 of node.

**Comment by jj0b** [comment]
I was able to fix the same error for myself on MacOS by switching to an environment where Python 2.7 was the default Python. 

node-gyp is not compatible with Python 3.x and libxmljs uses node-gyp.

**Comment by jmmalunao** [comment]
> I was able to fix the same error for myself on MacOS by switching to an environment where Python 2.7 was the default Python.
> 
> node-gyp is not compatible with Python 3.x and libxmljs uses node-gyp.

Installed Python2.7 some errors removed but still got build error with recommendation to install .NET Framework 2.0 SDK, installed and now all is working.

**Comment by DanielRuf** [comment]
It seems some of you do not have the required build tools (python2) and use some old one (node-waf was before node-gyp).

**Comment by DanielRuf** [comment]
I think we can close the initial issue as it was about libxmljs 0.0.7.

**Comment by DanielRuf** [comment]
node uses the environment variable  `PYTHON` to define the python2 path.

Windows users should do `npm i -g windows-build-tools` to install the needed dependencies.
