### ISSUE TITLE
Missing assert definition in wiki example for XSD

### ISSUE THREAD

**Issue by DanielRuf** [libxmljs/libxmljs#554]
In the wiki the XSD example does not define `assert`.

**Comment by KaustubhBadrike-GEP** [comment]
It is available in [Node.js Assertion Testing](https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message)

**Comment by DanielRuf** [comment]
I know but you should explicitely mention that and also add the `const assert = require('assert')` line.

**Comment by DanielRuf** [comment]
Because this is none of the current globals:

https://nodejs.org/api/globals.html

**Comment by DanielRuf** [comment]
```js
assert.equal(1, 2, 'not equal')
```

```
node test.js 
/home/druf/Schreibtisch/projects/assert-test/test.js:1
assert.equal(1, 2, 'not equal')
^

ReferenceError: assert is not defined
    at Object.<anonymous> (/home/druf/Schreibtisch/projects/assert-test/test.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by KaustubhBadrike-GEP** [comment]
Oh I see. I didn't bother to check for the imports since I was used to treating snippets as not necessarily complete (IDEs generally catch them when I actually use it). Nonetheless, it was incorrect to assume all asserts come from Node. Good catch!
