### ISSUE TITLE
libxmljs Isn't compiling with nodejs 12.16.3

### ISSUE THREAD

**Issue by jusech5** [libxmljs/libxmljs#573]
With previous version 12.16.2 everything is working well.
```sh
npm i

npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> deasync@0.1.20 install /home/user/myproject/node_modules/deasync
> node ./build.js

`linux-x64-node-12` exists; testing
Binary is fine; exiting

> libxmljs@0.19.7 install /home/user/myproject/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v72-linux-x64.tar.gz
node-pre-gyp http 302 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v72-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.7 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v72-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.7 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.7 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error bad download 
gypgyp  httphttp  GETGET https://nodejs.org/download/release/v12.16.3/node-v12.16.3-headers.tar.gz
 https://nodejs.org/download/release/v12.16.3/node-v12.16.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.16.3/node-v12.16.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.16.3/node-v12.16.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.16.3/node-v12.16.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.16.3/node-v12.16.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.16.3/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v12.16.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.16.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.16.3/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v12.16.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.16.3/SHASUMS256.txt
make: Entering directory '/home/user/myproject/node_modules/libxmljs/build'
make: Entering directory '/home/user/myproject/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: Entering directory '/home/user/myproject/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
rm: cannot remove './Release/.deps/Release/obj.target/xmljs/src/libxmljs.o.d.raw': No such file or directory
xmljs.target.mk:162: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory '/home/user/myproject/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-1052-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/user/myproject/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/user/myproject/node_modules/libxmljs/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/user/myproject/node_modules/libxmljs
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/user/myproject/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/user/myproject/node_modules/libxmljs/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/myproject/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.15.0-1052-aws
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/user/myproject/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/user/myproject/node_modules/libxmljs
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/user/myproject/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/user/myproject/node_modules/libxmljs/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
In file included from ../src/xml_attribute.h:5:0,
                 from ../src/xml_attribute.cc:2:
../src/libxmljs.h:7:17: fatal error: nan.h: No such file or directory
compilation terminated.
xmljs.target.mk:162: recipe for target 'Release/obj.target/xmljs/src/xml_attribute.o' failed
make: *** [Release/obj.target/xmljs/src/xml_attribute.o] Error 1
make: Leaving directory '/home/user/myproject/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-1052-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/user/myproject/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/user/myproject/node_modules/libxmljs/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/user/myproject/node_modules/libxmljs
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
In file included from ../src/xml_attribute.h:5:0,
                 from ../src/xml_attribute.cc:2:
../src/libxmljs.h:7:17: fatal error: nan.h: No such file or directory
compilation terminated.
xmljs.target.mk:162: recipe for target 'Release/obj.target/xmljs/src/xml_attribute.o' failed
make: *** [Release/obj.target/xmljs/src/xml_attribute.o] Error 1
make: Leaving directory '/home/user/myproject/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-1052-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/user/myproject/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/user/myproject/node_modules/libxmljs/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/user/myproject/node_modules/libxmljs
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.19.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.19.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-05-07T13_39_21_004Z-debug.log
```

**Comment by marudor** [comment]
My fork libxmljs2 (https://github.com/marudor/libxmljs2) works on node 12.16.3.

**Comment by Xaekai** [comment]
For anyone ending up here, make sure you don't have anything depending on older versions of iconv. My project using the 'irc' module was causing libxmljs to fail to compile because of it's older iconv, and when I manually edited it's package.json to use a newer one the problem vanished
