### ISSUE TITLE
This package doesn't work with yarn pnp 

### ISSUE THREAD

**Issue by cbonnissent** [libxmljs/libxmljs#586]
(node:207355) UnhandledPromiseRejectionWarning: Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/build/xmljs.node
Rejected candidate: /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/build/xmljs.node
Rejected candidate: /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/build/xmljs.node.js
Rejected candidate: /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/build/xmljs.node.json
Rejected candidate: /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/build/xmljs.node.node

Require stack:
- /home/charles/git/anakeen-platform-4/.yarn/cache/bindings-npm-1.3.1-67cd858d43-73c8aa7dd8.zip/node_modules/bindings/bindings.js
- /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/lib/bindings.js
- /home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/index.js
- /home/charles/git/anakeen-platform-4/module-validation/index.js
- /home/charles/git/anakeen-platform-4/anakeen-cli/utils/moduleInfo.js
- /home/charles/git/anakeen-platform-4/anakeen-cli/tasks/moduleInfo.js
- /home/charles/git/anakeen-platform-4/anakeen-cli/commands/analyzeModule.js
- /home/charles/git/anakeen-platform-4/.yarn/cache/yargs-npm-15.4.1-ca1c444de1-dbf687d6b9.zip/node_modules/yargs/index.js
- /home/charles/git/anakeen-platform-4/anakeen-cli/index.js
    at internalTools_makeError (/home/charles/git/anakeen-platform-4/.pnp.js:34055:34)
    at resolveUnqualified (/home/charles/git/anakeen-platform-4/.pnp.js:35094:13)
    at resolveRequest (/home/charles/git/anakeen-platform-4/.pnp.js:35118:14)
    at Object.resolveRequest (/home/charles/git/anakeen-platform-4/.pnp.js:35190:26)
    at Function.external_module_.Module._resolveFilename (/home/charles/git/anakeen-platform-4/.pnp.js:34288:34)
    at Function.external_module_.Module._load (/home/charles/git/anakeen-platform-4/.pnp.js:34153:48)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/home/charles/git/anakeen-platform-4/.yarn/cache/bindings-npm-1.3.1-67cd858d43-73c8aa7dd8.zip/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/home/charles/git/anakeen-platform-4/.yarn/unplugged/libxmljs-npm-0.19.7-fa6b6b2658/node_modules/libxmljs/lib/bindings.js:1:37)
(node:207355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:207355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by madelinecameron** [comment]
This package is broken for all node versions higher than 10. 

The update was supposed to be back in early Feb, came to check in on the status and figured I'd respond.

**Comment by cbonnissent** [comment]
I have used a symbolic link to make it work but there are securities issues with this package so I use libxml2 that have the same api, work in pnp and have no security issue

**Comment by mr-bjerre** [comment]
Do you have a link to libxml2? I can't find any with the same api
