### ISSUE TITLE
Fails to build on intel Mac running node version 16.13

### ISSUE THREAD

**Issue by zoeesilcock** [libxmljs/libxmljs#592]
This was working fine when running node version 14.16. I found a workaround to a similar build error in the `node-sass` package here: https://github.com/nodejs/node/issues/38367. By adding `CXXFLAGS="--std=c++14"` before `npm install` the build passes but leads to other errors in runtime.

Based on what I've read in other issues it seems that this package needs to be updated in order to support node version 16. For reference it looks like `node-sass` only changed the CXXFLAGS: https://github.com/sass/node-sass/pull/3091. That would presumably not be enough here since it fails at runtime when manually changing the CXXFLAGS.

Build error without workaround:
```
npm ERR! code 1
npm ERR! path /path/to/project/node_modules/libxmljs
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! CXX(target) Release/obj.target/xmljs/src/libxmljs.o
npm ERR! Failed to execute '/Users/me/.nvm/versions/node/v16.13.0/bin/node /Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/path/to/project/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/path/to/project/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v93-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v93-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.7 and node@16.13.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v93-darwin-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp info ok
npm ERR! gyp http GET https://nodejs.org/download/release/v16.13.0/node-v16.13.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.13.0/node-v16.13.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.13.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.13.0/SHASUMS256.txt
npm ERR! In file included from ../src/libxmljs.cc:3:
npm ERR! In file included from /Users/me/Library/Caches/node-gyp/16.13.0/include/node/v8.h:30:
npm ERR! /Users/me/Library/Caches/node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/Users/me/.nvm/versions/node/v16.13.0/bin/node" "/Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/path/to/project/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/path/to/project/node_modules/libxmljs/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /path/to/project/node_modules/libxmljs
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/me/.nvm/versions/node/v16.13.0/bin/node /Users/me/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/path/to/project/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/path/to/project/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/path/to/project/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 19.6.0
npm ERR! node-pre-gyp ERR! command "/Users/me/.nvm/versions/node/v16.13.0/bin/node" "/path/to/project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
npm ERR! node-pre-gyp ERR! cwd /path/to/project/node_modules/libxmljs
npm ERR! node-pre-gyp ERR! node -v v16.13.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok
```

Runtime error after workaround:
```
dyld: Symbol not found: __ZN2v87Isolate37AdjustAmountOfExternalAllocatedMemoryEx
  Referenced from: /path/to/project/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: flat namespace
```

**Comment by luckydonald** [comment]
Having the same initial problem with node 16.13.0.

**Comment by ulisesbocchio** [comment]
changing from `'CLANG_CXX_LANGUAGE_STANDARD': 'c++11' ` to `'CLANG_CXX_LANGUAGE_STANDARD': 'c++17'` solves the problem in BigSur with latest updates/Xcode tooling.
Also, hacking line `/Users/me/Library/Caches/node-gyp/16.13.0/include/node/v8-internal.h:492:38` from `remove_cv_t` to to the suggested `remove_cv` by the C++ compiler does the trick.
is there any way to set `'CLANG_CXX_LANGUAGE_STANDARD': 'c++17'` globally for npm/node-gyp?

**Comment by ulisesbocchio** [comment]
this works too btw: `CXXFLAGS="--std=c++17" npm install`

**Comment by SokichiFujita** [comment]
There is the similar issue with node v17.x on Apple Silicon M1 Macbook. But `CXXFLAGS="--std=c++17" npm install libxmljs` solved the error. Thank you.

**Comment by abarriel** [comment]
up pls
