### ISSUE TITLE
Unable to parse large XML files > 10MB

### ISSUE THREAD

**Issue by shunkica** [libxmljs/libxmljs#602]
When trying to parse XML larger than 10 MB, the parser fails with this error:

```
.../libxmljs@0.19.10/node_modules/libxmljs/lib/document.js:168
    return bindings.fromXml(string, options || {});
                    ^

Error: Extra content at the end of the document

    at Object.module.exports.fromXml (.../libxmljs@0.19.10/node_modules/libxmljs/lib/document.js:168:21)
    at Object.<anonymous> (.../index.js:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  domain: 1,
  code: 5,
  level: 3,
  column: 10026681,
  line: 1
}

```
After some investigation I found this is related to the default libxml limitation of 10MB.

I found there is a option `huge_tree` in lxml to disable this limitation and tried to pass this option like this to the parser but this results in the same error:
`
xmljs.parseXmlString(xml.toString('utf-8'),{huge_tree:true});`

**Comment by shunkica** [comment]
Duplicate of #372
