### ISSUE TITLE
parserInternal.h not found?

### ISSUE THREAD

**Issue by mureinik** [libxmljs/libxmljs#614]
When forcing npm to rebuild from source the compilation fails since its unable to find `parserInternal.h`:

```none
allon@computer:~/src/git/samplenode$ npm install --build-from-source libxmljs

> libxmljs@1.0.1 install /home/allon/src/git/samplenode/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

make: Entering directory '/home/allon/src/git/samplenode/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
../src/xml_sax_parser.cc:6:10: fatal error: parserInternals.h: No such file or directory
 #include "parserInternals.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
xmljs.target.mk:176: recipe for target 'Release/obj.target/xmljs/src/xml_sax_parser.o' failed
make: *** [Release/obj.target/xmljs/src/xml_sax_parser.o] Error 1
make: Leaving directory '/home/allon/src/git/samplenode/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/allon/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-202-generic
gyp ERR! command "/home/allon/.nvm/versions/node/v14.16.0/bin/node" "/home/allon/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/allon/src/git/samplenode/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/allon/src/git/samplenode/node_modules/libxmljs/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/allon/src/git/samplenode/node_modules/libxmljs
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/allon/.nvm/versions/node/v14.16.0/bin/node /home/allon/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/allon/src/git/samplenode/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/allon/src/git/samplenode/node_modules/libxmljs/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/allon/src/git/samplenode/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.15.0-202-generic
node-pre-gyp ERR! command "/home/allon/.nvm/versions/node/v14.16.0/bin/node" "/home/allon/src/git/samplenode/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/allon/src/git/samplenode/node_modules/libxmljs
node-pre-gyp ERR! node -v v14.16.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok
Failed to execute '/home/allon/.nvm/versions/node/v14.16.0/bin/node /home/allon/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/allon/src/git/samplenode/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/allon/src/git/samplenode/node_modules/libxmljs/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN node-fetch@2.6.9 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN samplenode@1.0.0 No description
npm WARN samplenode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@1.0.1 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/allon/.npm/_logs/2023-03-30T18_20_14_564Z-debug.log
```

(Reproduced on several different Node.js versions and several different platforms, pasting here one example)

**Comment by rchipka** [comment]
Looks like we need to find a way to init submodules before building from source after installing

Try after `npm run init-submodules` or `git submodule update --init --recursive`

**Comment by mureinik** [comment]
Maybe I'm being daft, but there's no `init-submodules` script there - I'm not cloning it and trying to build, I'm trying to install it as a module in another project, but compile the C part locally instead of depending on a prebuilt binary

**Comment by mureinik** [comment]
@rchipka no improvement, unfortunately. In fact, I think we're worse off:\
With `--build-from-source` I still get an error about `parserInternal.h`, and another new error about failing to `git run init-submodules` (presumably because init-submodules assumes it would be run on `libxmljs`' root folder, but in fact its being executed on the root of the project that is trying to install it, which in this case isn't even a git project

```none
allon@allon-z440:~/src/untracked/samplenode$ npm install --build-from-source libxmljs

> libxmljs@1.0.2 install /home/allon/src/untracked/samplenode/node_modules/libxmljs
> node-pre-gyp install --loglevel http || (npm run init && npm run build)

make: Entering directory '/home/allon/src/untracked/samplenode/node_modules/libxmljs/build'
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
../src/xml_sax_parser.cc:6:10: fatal error: parserInternals.h: No such file or directory
 #include "parserInternals.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
xmljs.target.mk:166: recipe for target 'Release/obj.target/xmljs/src/xml_sax_parser.o' failed
make: *** [Release/obj.target/xmljs/src/xml_sax_parser.o] Error 1
make: Leaving directory '/home/allon/src/untracked/samplenode/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-202-generic
gyp ERR! command "/home/allon/.nvm/versions/node/v10.13.0/bin/node" "/home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--loglevel=http" "--module=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/allon/src/untracked/samplenode/node_modules/libxmljs
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/allon/.nvm/versions/node/v10.13.0/bin/node /home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --loglevel=http --module=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/home/allon/src/untracked/samplenode/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.15.0-202-generic
node-pre-gyp ERR! command "/home/allon/.nvm/versions/node/v10.13.0/bin/node" "/home/allon/src/untracked/samplenode/node_modules/.bin/node-pre-gyp" "install" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/allon/src/untracked/samplenode/node_modules/libxmljs
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok
Failed to execute '/home/allon/.nvm/versions/node/v10.13.0/bin/node /home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --loglevel=http --module=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> libxmljs@1.0.2 init /home/allon/src/untracked/samplenode/node_modules/libxmljs
> node scripts/init.js

Initializing submodules

> libxmljs@1.0.2 init-submodules /home/allon/src/untracked/samplenode/node_modules/libxmljs
> git submodule update --init --recursive

fatal: not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! libxmljs@1.0.2 init-submodules: `git submodule update --init --recursive`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the libxmljs@1.0.2 init-submodules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/allon/.npm/_logs/2023-03-31T13_45_18_262Z-debug.log
child_process.js:651
    throw err;
    ^

Error: Command failed: npm run init-submodules
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Object.<anonymous> (/home/allon/src/untracked/samplenode/node_modules/libxmljs/scripts/init.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@1.0.2 init: `node scripts/init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@1.0.2 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/allon/.npm/_logs/2023-03-31T13_45_18_282Z-debug.log
npm WARN node-fetch@2.6.9 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN samplenode@1.0.0 No description
npm WARN samplenode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@1.0.2 install: `node-pre-gyp install --loglevel http || (npm run init && npm run build)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/allon/.npm/_logs/2023-03-31T13_45_18_382Z-debug.log

```

**Comment by rchipka** [comment]
I'd like to avoid bundling the entire libxml2 source code with the library if we don't have to. 

The `node_modules` directory already has a significant bloat problem and if one less library contributes to this, then I'd consider that a win.

If [this](https://github.com/nodejs/node-gyp/issues/9) was a thing then we'd have an easy way to accomplish this. I've tried the solution they mentioned (gyp actions), but that doesn't work for windows builds.

**Comment by rchipka** [comment]
What we need is a way to hook into (or otherwise preempt) node-pre-gyp/node-gyp so that we can do the proper initialization before build.

Having this infrastructure setup would be beneficial anyways since libxmljs now has a fairly complex build infrastructure if you truly want to start from scratch (submodules, cmake configure, SWIG, then build).

**Comment by rchipka** [comment]
Actually, looking at the log, it's not a cwd issue.

We won't be able to init submodules from the npm packaged version unless we include the `.git` directory. Hmm.

**Comment by rchipka** [comment]
Alright, for simplicity's sake I'm thinking we're just gonna have to go back to packaging submodules. 

I think I've got an answer that at least keeps git-sourced installations (eg. CI builds) simple by automating submodule init in those instances.

**Comment by rchipka** [comment]
![image](https://user-images.githubusercontent.com/7538316/229174796-610be718-5822-4cc3-a2b9-9c31e99d5343.png)

**Comment by rchipka** [comment]
@mureinik hoping we're good now

![Screenshot 2023-03-31 at 12 40 17 PM](https://user-images.githubusercontent.com/7538316/229179837-359e3b45-71d9-4cfa-80d3-3270d8dde882.png)

**Comment by mureinik** [comment]
@rchipka unfortunately still not :-(
Definitely making progress, but now it's failing because it can't require `nan`:

```none
allon@allon-z440:~/src/untracked/samplenode$ npm install --build-from-source libxmljs

> libxmljs@1.0.3 preinstall /home/allon/src/untracked/samplenode/node_modules/libxmljs
> node scripts/preinstall.js

Initializing git repo
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/allon/src/untracked/samplenode/node_modules/libxmljs/.git/

> libxmljs@1.0.3 install /home/allon/src/untracked/samplenode/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-202-generic
gyp ERR! command "/home/allon/.nvm/versions/node/v10.13.0/bin/node" "/home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/allon/src/untracked/samplenode/node_modules/libxmljs
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/allon/.nvm/versions/node/v10.13.0/bin/node /home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/home/allon/src/untracked/samplenode/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.15.0-202-generic
node-pre-gyp ERR! command "/home/allon/.nvm/versions/node/v10.13.0/bin/node" "/home/allon/src/untracked/samplenode/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/allon/src/untracked/samplenode/node_modules/libxmljs
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok
Failed to execute '/home/allon/.nvm/versions/node/v10.13.0/bin/node /home/allon/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/allon/src/untracked/samplenode/node_modules/libxmljs/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN node-fetch@2.6.9 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN samplenode@1.0.0 No description
npm WARN samplenode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@1.0.3 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/allon/.npm/_logs/2023-03-31T16_42_10_111Z-debug.log
```

With my local copy of libxmljs, moving `nan` from the `devDependencies` to `dependencies` solves the issue, but I'm not sure this is the right move.

**Comment by mureinik** [comment]
Alternatively, if the consumer wants to use `--build-from-source` they can install `nan` directly.

I'm guessing that using `--build-from-source` isn't a common practice (e.g., in my usecase, I'm using it on a very old CentOS machine to force libxml to be compiled with an older glibc that the packaged binary). Perhaps instead of "dirtying" the dependencies, defining `nan` in the `peerDependencies` and documenting it in the README is a better move?

**Comment by riley-ciq** [comment]
My bad, sorry for the whiplash here. I was fixing the duplicate NaN dependency and removed it from the wrong section.

I have no issues with keeping it in "dependencies" since that should contain everything necessary to build the C++ code imo.

**Comment by rchipka** [comment]
My bad, sorry for the whiplash here. I was fixing the duplicate NaN dependency and removed it from the wrong section.

I have no issues with keeping it in "dependencies" since that should contain everything necessary to build the C++ code imo.

**Comment by mureinik** [comment]
@rchipka Thanks!
I can confirm that with 1.0.6 it installs cleanly on both my Windows and Linux machines.
Closing this bug.

**Comment by rchipka** [comment]
@mureinik Awesome, thanks for confirming and for the help on this one!
