### ISSUE TITLE
libxmljs install failed in node20.5.1+alpine3.18

### ISSUE THREAD

**Issue by LynnChow** [libxmljs/libxmljs#632]
Hi,

Please help me out with install libxmljs on node20.5.1+alpine3.18.
Thank you!

ffbd2ed1d231:/home# cat /etc/alpine-release
3.18.3
ffbd2ed1d231:/home# nodejs --version
v20.5.1
ffbd2ed1d231:/home# npm install libxmljs
npm notice
npm notice New patch version of npm available! 9.8.0 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice
npm ERR! code 1
npm ERR! path /home/node_modules/libxmljs
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --loglevel http -j max
npm ERR! make: Entering directory '/home/node_modules/libxmljs/build'
npm ERR!   CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
npm ERR!   CXX(target) Release/obj.target/xmljs/src/libxml2.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/buf.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/catalog.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/chvalid.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/dict.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/encoding.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/entities.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/error.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/globals.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/hash.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/HTMLparser.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/HTMLtree.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/legacy.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/list.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/parser.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/parserInternals.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/pattern.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/relaxng.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/SAX2.o
npm ERR!   CC(target) Release/obj.target/xmljs/vendor/libxml2/SAX.o
npm ERR! make: Leaving directory '/home/node_modules/libxmljs/build'
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --jobs=max --module=/home/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/node_modules/libxmljs/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v1.0.9/node-v115-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v1.0.9/node-v115-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs@1.0.9 and node@20.5.1 (node-v115 ABI, musl) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v1.0.9/node-v115-linux-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.1 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp http GET https://unofficial-builds.nodejs.org/download/release/v20.5.1/node-v20.5.1-headers.tar.gz
npm ERR! gyp http 200 https://unofficial-builds.nodejs.org/download/release/v20.5.1/node-v20.5.1-headers.tar.gz
npm ERR! gyp http GET https://unofficial-builds.nodejs.org/download/release/v20.5.1/SHASUMS256.txt
npm ERR! gyp http 200 https://unofficial-builds.nodejs.org/download/release/v20.5.1/SHASUMS256.txt
npm ERR! ../vendor/libxml2/buf.c: In function 'xmlBufMemoryError':
npm ERR! ../vendor/libxml2/buf.c:94:5: warning: too many arguments for format [-Wformat-extra-args]
npm ERR!    94 |     __xmlSimpleError(XML_FROM_BUFFER, XML_ERR_NO_MEMORY, NULL, NULL, extra);
npm ERR!       |     ^~~~~~~~~~~~~~~~
npm ERR! ../vendor/libxml2/buf.c: In function 'xmlBufOverflowError':
npm ERR! ../vendor/libxml2/buf.c:109:5: warning: too many arguments for format [-Wformat-extra-args]
npm ERR!   109 |     __xmlSimpleError(XML_FROM_BUFFER, XML_BUF_OVERFLOW, NULL, NULL, extra);
npm ERR!       |     ^~~~~~~~~~~~~~~~
npm ERR! In file included from ../src/xml_sax_parser.cc:3:
npm ERR! ../../nan/nan.h: In function 'bool Nan::IdleNotification(int)':
npm ERR! ../../nan/nan.h:686:63: warning: 'bool v8::Isolate::IdleNotificationDeadline(double)' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
npm ERR!   686 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
npm ERR!       |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm ERR!   687 |         idle_time_in_ms * 0.001);
npm ERR!       |         ~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! In file included from /root/.cache/node-gyp/20.5.1/include/node/v8-initialization.h:13,
npm ERR!                  from /root/.cache/node-gyp/20.5.1/include/node/v8.h:34,
npm ERR!                  from /root/.cache/node-gyp/20.5.1/include/node/node.h:73,
npm ERR!                  from ../../nan/nan.h:60:
npm ERR! /root/.cache/node-gyp/20.5.1/include/node/v8-isolate.h:1293:8: note: declared here
npm ERR!  1293 |   bool IdleNotificationDeadline(double deadline_in_seconds);
npm ERR!       |        ^~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../vendor/libxml2/encoding.c: In function 'xmlEncodingErrMemory':
npm ERR! ../vendor/libxml2/encoding.c:86:5: warning: too many arguments for format [-Wformat-extra-args]
npm ERR!    86 |     __xmlSimpleError(XML_FROM_I18N, XML_ERR_NO_MEMORY, NULL, NULL, extra);
npm ERR!       |     ^~~~~~~~~~~~~~~~
npm ERR! ../src/xml_sax_parser.cc: In member function 'void libxmljs::XmlSaxParser::Callback(const char*, int, v8::Local<v8::Value>*)':
npm ERR! ../src/xml_sax_parser.cc:119:22: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
npm ERR!   119 |     Nan::MakeCallback(this->handle(), v8::Local<v8::Function>::Cast(emit_v),
npm ERR!       |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR!   120 |                       argc + 1, args);
npm ERR!       |                       ~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan.h:1030:46: note: declared here
npm ERR!  1030 |   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
npm ERR!       |                                              ^~~~~~~~~~~~
npm ERR! ../vendor/libxml2/encoding.c: In function 'xmlCharEncCloseFunc':
npm ERR! ../vendor/libxml2/encoding.c:2780:12: warning: variable 'handler_in_list' set but not used [-Wunused-but-set-variable]
npm ERR!  2780 |     int i, handler_in_list = 0;
npm ERR!       |            ^~~~~~~~~~~~~~~
npm ERR! ../vendor/libxml2/entities.c: In function 'xmlEntitiesErrMemory':
npm ERR! ../vendor/libxml2/entities.c:81:5: warning: too many arguments for format [-Wformat-extra-args]
npm ERR!    81 |     __xmlSimpleError(XML_FROM_TREE, XML_ERR_NO_MEMORY, NULL, NULL, extra);
npm ERR!       |     ^~~~~~~~~~~~~~~~
npm ERR! In file included from ../src/libxml2.cc:9:
npm ERR! ../../nan/nan.h: In function 'bool Nan::IdleNotification(int)':
npm ERR! ../../nan/nan.h:686:63: warning: 'bool v8::Isolate::IdleNotificationDeadline(double)' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
npm ERR!   686 |     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
npm ERR!       |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm ERR!   687 |         idle_time_in_ms * 0.001);
npm ERR!       |         ~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! In file included from /root/.cache/node-gyp/20.5.1/include/node/v8-initialization.h:13,
npm ERR!                  from /root/.cache/node-gyp/20.5.1/include/node/v8.h:34,
npm ERR!                  from /root/.cache/node-gyp/20.5.1/include/node/node.h:73,
npm ERR!                  from ../../nan/nan.h:60:
npm ERR! /root/.cache/node-gyp/20.5.1/include/node/v8-isolate.h:1293:8: note: declared here
npm ERR!  1293 |   bool IdleNotificationDeadline(double deadline_in_seconds);
npm ERR!       |        ^~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../src/libxml2.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE withStructuredErrors(Nan::NAN_METHOD_ARGS_TYPE)':
npm ERR! ../src/libxml2.cc:3036:35: error: invalid cast from type 'std::nullptr_t' to type 'void*'
npm ERR!  3036 |         xmlSetStructuredErrorFunc(reinterpret_cast<void*>(NULL), XmlSyntaxError::PushToArray);
npm ERR!       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../src/libxml2.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE withGenericErrors(Nan::NAN_METHOD_ARGS_TYPE)':
npm ERR! ../src/libxml2.cc:3058:32: error: invalid cast from type 'std::nullptr_t' to type 'void*'
npm ERR!  3058 |         xmlSetGenericErrorFunc(reinterpret_cast<void*>(NULL), XmlSyntaxError::GenericPushToArray);
npm ERR!       |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! ../vendor/libxml2/HTMLtree.c: In function 'htmlSaveErrMemory':
npm ERR! ../vendor/libxml2/HTMLtree.c:355:5: warning: too many arguments for format [-Wformat-extra-args]
npm ERR!   355 |     __xmlSimpleError(XML_FROM_OUTPUT, XML_ERR_NO_MEMORY, NULL, NULL, extra);
npm ERR!       |     ^~~~~~~~~~~~~~~~
npm ERR! make: *** [xmljs.target.mk:178: Release/obj.target/xmljs/src/libxml2.o] Error 1
npm ERR! make: *** Waiting for unfinished jobs....
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 3.10.0-1160.59.1.el7.x86_64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--jobs=max" "--module=/home/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/node_modules/libxmljs/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm ERR! gyp ERR! cwd /home/node_modules/libxmljs
npm ERR! gyp ERR! node -v v20.5.1
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --jobs=max --module=/home/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/node_modules/libxmljs/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Linux 3.10.0-1160.59.1.el7.x86_64
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/home/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http" "-j" "max"
npm ERR! node-pre-gyp ERR! cwd /home/node_modules/libxmljs
npm ERR! node-pre-gyp ERR! node -v v20.5.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-08-25T08_32_08_984Z-debug-0.log

**Comment by lucasadrianof** [comment]
It looks like `libxmljs` is currently not building and publishing the Node 20 binaries so `node-pre-gyp` is trying to build it while installing the dependency, which errors on alpine for some reason.

Looking at the GH actions on this repo it seems like all builds are executed on a `ubuntu` container, what you could do is run a multi-stage build and manually install `libxmljs` on a node:20 ubuntu/debian distro and copy the `libxmljs` binaries to your alpine image afterwards (at least until this package start publishing the Node 20 binaries too).

**Comment by LynnChow** [comment]
> It looks like `libxmljs` is currently not building and publishing the Node 20 binaries so `node-pre-gyp` is trying to build it while installing the dependency, which errors on alpine for some reason.
> 
> Looking at the GH actions on this repo it seems like all builds are executed on a `ubuntu` container, what you could do is run a multi-stage build and manually install `libxmljs` on a node:20 ubuntu/debian distro and copy the `libxmljs` binaries to your alpine image afterwards (at least until this package start publishing the Node 20 binaries too).

Hi,

Thanks for the solution, and when I run 'npm install libxmljs' on a node20.5.1 container, it can finally fall back to source compile with node-gyp successfully.
So, could you please tell me where to find the `libxmljs` binaries or how to generate the `libxmljs` package then?

Thank you very much!!

**Comment by lucasadrianof** [comment]
> > It looks like `libxmljs` is currently not building and publishing the Node 20 binaries so `node-pre-gyp` is trying to build it while installing the dependency, which errors on alpine for some reason.
> > Looking at the GH actions on this repo it seems like all builds are executed on a `ubuntu` container, what you could do is run a multi-stage build and manually install `libxmljs` on a node:20 ubuntu/debian distro and copy the `libxmljs` binaries to your alpine image afterwards (at least until this package start publishing the Node 20 binaries too).
> 
> Hi,
> 
> Thanks for the solution, and when I run 'npm install libxmljs' on a node20.5.1 container, it can finally fall back to source compile with node-gyp successfully. So, could you please tell me where to find the `libxmljs` binaries or how to generate the `libxmljs` package then?
> 
> Thank you very much!!

No problem, glad it worked!

The binaries for each version are published on the [Releases page](https://github.com/libxmljs/libxmljs/releases) of this repo. They use [node-pre-gyp versioning](https://github.com/mapbox/node-pre-gyp#versioning) to name the release, so that's why you'll see a bunch of different versions for the same package version.

For your second question, I think you'd need to fork this repo and publish a new package version with the missing binaries, which would contain the Node v20 release too. [This is how](https://github.com/libxmljs/libxmljs/blob/master/.github/workflows/test-deploy.yml#L94-L130) these binaries are currently compiled for Node versions 16, 17, and 18. You could also open a PR on this repo adding Node 20 to that list, but you'd need to wait for it to get merged and for a new release to be published before effectively using it.

**Comment by PaoloDiBello** [comment]
Please add support for node 20 too
