### ISSUE TITLE
libxmljs using NODE_MODULE_VERSION 93 but need NODE_MODULE_VERSION 108 for node 18

### ISSUE THREAD

**Issue by JESii** [libxmljs/libxmljs#633]
I'm upgrading from node 16 to node 18 and running into an issue with this module. I've installed everything fresh. When trying to start the api server, I'm getting the following error:
```

yarn run v1.22.19
warning ../../../../package.json: No license field
$ bash ./run/env/demo/restart.sh
USING DEFAULT CONFIG
USING DEMO CONFIG
/Users/jseidel/ppg/makena/makena-client-portal/api/node_modules/bindings/bindings.js:91
        throw e
        ^

Error: The module '/Users/jseidel/ppg/makena/makena-client-portal/api/node_modules/libxmljs/build/Release/xmljs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/Users/jseidel/ppg/makena/makena-client-portal/api/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/Users/jseidel/ppg/makena/makena-client-portal/api/node_modules/libxmljs/dist/lib/bindings/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/jseidel/ppg/makena/makena-client-portal/api/node_modules/libxmljs/dist/lib/node.js:19:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.0
error Command failed with exit code 1.
```
I'm running the latest version of libxmljs - 1.0.9, and I see there is a node 18 binary on the releases page.

Not sure where to go with this so would appreciate some suggestions. Thanks.

**Comment by JESii** [comment]
Turns out to be pretty simple:
```
rm -rf node_modules/libxmljs
yarn add libxmljs
```
