### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by jayant93** [libxmljs/libxmljs#634]
npm ERR! path C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2
npm ERR! command failed
npm ERR! command C:\Program Files\git\bin\bash.exe -c node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\LAVDKEHW10CP-3398\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --loglevel=http --module=C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2\build\Release\xmljs.node --module_name=xmljs --module_path=C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108 --msvs_version=2022' (1)
npm ERR! node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.29.0/node-v108-win32-x64-unknown.tar.gz
npm ERR! node-pre-gyp http download proxy agent configured using: "http://opuspx.op.fi:8085"
npm ERR! node-pre-gyp ERR! install request to https://github.com/marudor/libxmljs2/releases/download/v0.29.0/node-v108-win32-x64-unknown.tar.gz failed, reason: unable to verify the first certificate
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs2@0.29.0 and node@18.14.2 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error request to https://github.com/marudor/libxmljs2/releases/download/v0.29.0/node-v108-win32-x64-unknown.tar.gz failed, reason: unable to verify the first certificate
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.14.2 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp http GET https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.14.2/node-v18.14.2-headers.tar.gz failed, reason: unable to verify the first certificate
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\LAVDKEHW10CP-3398\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LAVDKEHW10CP-3398\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=C:\\Users\\B725550\\git\\wmp-message-translator\\node_modules\\libxmljs2\\build\\Release\\xmljs.node" "--module_name=xmljs" "--module_path=C:\\Users\\B725550\\git\\wmp-message-translator\\node_modules\\libxmljs2\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108" "--msvs_version=2022"
npm ERR! gyp ERR! cwd C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2
npm ERR! gyp ERR! node -v v18.14.2
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\LAVDKEHW10CP-3398\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --loglevel=http --module=C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2\build\Release\xmljs.node --module_name=xmljs --module_path=C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108 --msvs_version=2022' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\B725550\git\wmp-message-translator\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\B725550\\git\\wmp-message-translator\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
npm ERR! node-pre-gyp ERR! cwd C:\Users\B725550\git\wmp-message-translator\node_modules\libxmljs2
npm ERR! node-pre-gyp ERR! node -v v18.14.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\LAVDKEHW10CP-3398\AppData\Local\npm-cache\_logs\2023-09-22T08_15_03_568Z-debug-0.log

**Comment by jayant93** [comment]
Tried deleting node modules 
tried cleaning npm cache
installled node-gyp
install windows sdk 10
installed c++ tools
still not working 
npm install --msvs_version=2022 worked for one time then starts failing again
